name: Reach

on:
  push:
    branches: main
  schedule:
    - cron: '0 */8 * * *' # every 8 hours

permissions: read-all

jobs:
  reach-linux-openssl:
    permissions: write-all
    name: Top 1000 Reachability Test (Linux-OpenSSL)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Generate
      run: mkdir build && cd build && cmake -G 'Unix Makefiles' ..
    - name: Build
      run: cd build && cmake --build .
    - name: Install
      run: cd build && sudo cmake --install . --config Debug
    - name: quicreach *
      run: /usr/local/lib/quicreach '*' --parallel 8 --stats --csv build/data.csv
    - name: Save results
      run: |
        git checkout data
        git pull
        tail -n 1 build/data.csv >> data.csv
        git config user.email "quicdev@microsoft.com"
        git config user.name "QUIC Dev[bot]"
        git add data.csv
        git status
        git commit -m "Latest Reachability Results"
        git push
        git checkout main
  reach-windows-schannel:
    permissions: write-all
    name: Top 1000 Reachability Test (Windows-Schannel)
    needs: []
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Generate
      run: mkdir build && cd build && cmake -G 'Visual Studio 17 2022' -A x64 -DQUIC_TLS=schannel ..
    - name: Build
      run: cd build && cmake --build . --config Debug
    - name: Install
      run: cd build && cmake --install . --config Debug
    - name: quicreach *
      run: |
        & 'C:/Program Files/quicreach/lib/quicreach' '*' --parallel 8 --stats --csv build/data.csv
